# Generated by Django 5.2.15 on 2026-06-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
